name: skrtu
description: skrtu_video

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluro: "^1.6.3"
  video_player: ^0.10.11+1
  chewie: ^0.9.10
  like_button: ^1.0.0
  photo_view: ^0.9.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  full_screen_menu: 0.1.2
  flutter_staggered_grid_view: ^0.3.0
  dash_chat: ^1.1.9
  image_picker: ^0.6.7+1
  flutter_showcase: ^0.1.0
  font_awesome_flutter: ^8.8.1
#  firebase_storage: ^3.1.6
#  cloud_firestore: ^0.13.6
#  flutter_staggered_animations: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - imgs/index1.png
    - imgs/index1_select.png
    - imgs/msg.png
    - imgs/msg_select.png
    - imgs/video_select.png
    - imgs/video.png
    - imgs/find_select.png
    - imgs/find.png
    - imgs/me.png
    - imgs/me_select.png
    - imgs/img_default.png
    - imgs/discuss.png
    - imgs/team.png
    - imgs/room.png
    - imgs/user_default.png
    - imgs/care.png
    - imgs/history.png
    - imgs/collect.png
    - imgs/order.png
    - imgs/fuli.png
    - imgs/shop.png
    - imgs/fankui.png
    - imgs/set.png
    - imgs/sun.png
    - imgs/night.png
    - imgs/version.png
    - imgs/exit.png
    - imgs/level.png
    - imgs/level-1.png
    - imgs/level-2.png
    - imgs/idea.png
    - imgs/artical.png
    - imgs/put_video.png
    - imgs/answer.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
